name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest ]
        python-version: [ 3.7, 3.8, 3.9, '3.10' ]

    env:
      USING_COVERAGE: "3.9"

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install system requirements
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libpango-1.0-0 libpangoft2-1.0-0

      - name: Install system requirements
        if: matrix.platform == 'macos-latest'
        run: |
          brew update
          brew install pango libffi

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          make deps

      - name: Run tox
        run: |
          make tox
